spring:
  application:
    name: item-service
   
    rabbitmq:
    host: 192.168.204.128
    port: 5672
    username: admin
    password: admin
    
server:
  port: 8001
  
---
spring:
  profiles: item1

server:
  port: 8001
  
---
spring:
  profiles: item2

server:
  port: 8002